name    'st01tkh-mingw'
version '0.1.0'
source 'https://github.com/st01tkh/puppet-mingw'
author 'st01tkh'
license 'Apache License, Version 2.0'
summary 'Setup MinGW'
description 'Setup MinGW'
project_page 'https://github.com/st01tkh/puppet-mingw'
dependency 'puppetlabs/stdlib', '>= 1.0.0'
dependency 'chocolatey/chocolatey', '>= 1.2.0'
